name: Build and Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: codeberg-small
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install npm dependencies
        uses: docker://hugomods/hugo:std-node-lts-0.152.2
        with:
          args: npm install

      - name: Build Hugo site
        uses: docker://hugomods/hugo:std-node-lts-0.152.2
        with:
          args: --minify

      - name: Deploy to S3
        uses: docker://amazon/aws-cli:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        with:
          args: s3 sync public s3://${{ secrets.S3_BUCKET }} --delete
